[project]
name = "exapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bokeh>=3.7.3",
    "icechunk>=0.2.15",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "llvmlite>=0.44.0",
    "matplotlib>=3.10.3",
    "obstore>=0.6.0",
    "s3fs>=2025.5.1",
    "numba>=0.60.0",
    "xpublish>=0.1.0",
    "zarr>=3.0.8",
    "xpublish-wms>=0.13.2",
    "dask>=2025.5.1",
    "distributed>=2025.5.1",
    "coiled>=1.101.1",
    "xarray>=2025.4.0",
    "pooch>=1.8.2",
    "ipython>=9.3.0",
    "jupyter-server-proxy>=4.4.0",
    "ipyleaflet>=0.19.2",
    "pre-commit>=4.2.0",
]
