[project]
name = "exapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.60",
    "dask>=2025.5.1",
    "icechunk>=1.1.4",
    "mangum>=0.19.0",
    "odc-geo>=0.4.10",
    "pooch>=1.8.2",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "titiler>=0.24.2",
    "xarray>=2025.6.1",
    "xpublish>=0.4.1",
    "xpublish-tiles>=0.3.4",
]
