env:
  AWS_DEFAULT_REGION: us-west-2
  ECR_REPOSITORY: ocr
  IMAGE_TAG: tiles-latest
  LAMBDA_FUNCTION_NAME: ocr-xpublish-tiles

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::631969445205:role/github-action-role
          role-session-name: ocr-xpublish-role-session
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: login ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build image
        run: |
          docker build --provenance=false --platform linux/amd64 -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: tag image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG 631969445205.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: push image to ECR
        run: |
          docker push 631969445205.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: create or update lambda
        run: |
          IMAGE_URI=631969445205.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

          if aws lambda get-function --function-name $LAMBDA_FUNCTION_NAME 2>/dev/null; then
            echo "updating func"
            aws lambda update-function-code \
              --function-name $LAMBDA_FUNCTION_NAME \
              --image-uri $IMAGE_URI
          else
            echo "create new func"
            aws lambda create-function \
              --function-name $LAMBDA_FUNCTION_NAME \
              --package-type Image \
              --code ImageUri=$IMAGE_URI \
              --role arn:aws:iam::631969445205:role/ocr \
              --timeout 60 \
              --memory-size 2048
          fi
      - name: Wait for Lambda update to finish
        run: |
          for i in {1..30}; do
            STATUS=$(aws lambda get-function-configuration --function-name $LAMBDA_FUNCTION_NAME --query 'LastUpdateStatus' --output text)
            if [ "$STATUS" = "Successful" ]; then
              break
            fi
            echo "Waiting for Lambda update to finish... ($STATUS)"
            sleep 5
          done
