name: Deploy to AWS Lambda
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  AWS_DEFAULT_REGION: us-west-2
  ECR_REPOSITORY: ocr
  LAMBDA_FUNCTION_NAME: ocr-custom

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::631969445205:role/github-action-role
          role-session-name: ocr-xpublish-role-session
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build --provenance=false --platform linux/amd64 -t $ECR_REPOSITORY .

      - name: Tag Docker image
        run: |
          IMAGE_TAG=latest

          docker tag $ECR_REPOSITORY:$IMAGE_TAG 631969445205.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=latest

          docker push 631969445205.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Lambda function
        run: |
          IMAGE_TAG=latest

          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --image-uri 631969445205.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Wait for Lambda update to finish
        run: |
          for i in {1..30}; do
            STATUS=$(aws lambda get-function-configuration --function-name $LAMBDA_FUNCTION_NAME --query 'LastUpdateStatus' --output text)
            if [ "$STATUS" = "Successful" ]; then
              break
            fi
            echo "Waiting for Lambda update to finish... ($STATUS)"
            sleep 5
          done

      - name: Set LOGFIRE_PROJECT_TOKEN environment variable
        run: |
          aws lambda update-function-configuration \
            --function-name $LAMBDA_FUNCTION_NAME \
            --environment "Variables={LOGFIRE_PROJECT_TOKEN=${{ secrets.LOGFIRE_PROJECT_TOKEN }}}"
